### ISSUE TITLE
No individual object posts

### ISSUE THREAD

**Issue by aejolene** [matrix-msu/kora-connect#4]
-Moving this over from my Questions issue-
After I created my gallery, clicking on the individual objects threw Page Not Found error. Link to my test gallery is [here](http://vaarchaeology.matrix.msu.edu/index.php/reports/). 

There are no individual posts or pages for the objects in the gallery/library.

**Comment by aejolene** [comment]
I was able to get an object to display by individually creating an object from my library (which still has a lot of "undefined" values) http://vaarchaeology.matrix.msu.edu/index.php/2016/08/11/item-1/

 http://vaarchaeology.matrix.msu.edu/wp-content/plugins/kora/fullrecord.php?kid=97-352-1

But the same doesn't work with the gallery. FYI, the url to the non-functional gallery object page is:

http://vaarchaeology.matrix.msu.edu/index.php/reports/wp-content/plugins/kora/fullrecord.php?kid=97-352-1 

^Looks like the index.php in that path is an issue.

**Comment by seilagonzalez** [comment]
We changed the restful to be able to display, maybe we did something wrong. Could you please provide pid and sid for me. Thanks.

**Comment by aejolene** [comment]
PID 151
SID 850

**Comment by seilagonzalez** [comment]
so that content is working for me
http://dev2.matrix.msu.edu/wp-kora-plugin/?page_id=176

Click on the link. Anthony said maybe it's something with your wp installation.

**Comment by aejolene** [comment]
Yes! That works. I'm here on campus for the week and plan to essentially
start over beginning this evening. Thanks a lot.

**Comment by aejolene** [comment]
Hi all. So I rebuilt everything and it looks like I'm having an issue when I create a KORA Gallery element on a page:
http://vaarchaeology.matrix.msu.edu/index.php/rocketts/

However, when I add an individual object from library, I can get to the full record
http://vaarchaeology.matrix.msu.edu/index.php/rocketts-individual-records/

**Comment by watrall** [comment]
closing this because it is out of date.
