### ISSUE TITLE
Plugin incompatibility

### ISSUE THREAD

**Issue by aejolene** [matrix-msu/kora-connect#5]
At Ethan's request, I'm logging this one as an issue. When KORA is activated, it breaks a plugin called Tailor that I'm using. Here are screenshots of what it's supposed to look like (KORA Disabled) vs. what happens when KORA is activated.
![tailor_on_jolenesdomain](https://cloud.githubusercontent.com/assets/13810938/17735905/eb2616c0-6452-11e6-830a-645206eb7bef.png)
![tailor_on_matrix](https://cloud.githubusercontent.com/assets/13810938/17735911/f2237936-6452-11e6-84ad-22f3083c97a2.png)

**Comment by watrall** [comment]
Closing because I think things have been resolved
