### ISSUE TITLE
Theme behavior

### ISSUE THREAD

**Issue by aejolene** [matrix-msu/kora-connect#6]
I started with a really basic Twenty Sixteen theme, added some KORA content and then switched themes to https://wordpress.org/themes/sparkling/. After I turned on the KORA plugin, I saw a combination of styling from both themes. 

**Without KORA:**
![correctdisplay](https://cloud.githubusercontent.com/assets/13810938/17749190/a3f407e8-648a-11e6-983f-3189f9b23ef3.png)

**With KORA**
![themesmixed](https://cloud.githubusercontent.com/assets/13810938/17749197/b02e2430-648a-11e6-9648-36b2ea02064d.png)

**Comment by aejolene** [comment]
After some testing, it looks like the plugin may actually be bringing some styles from the Twenty Thirteen theme that you all are starting from.

**Comment by aejolene** [comment]
Hi all.
The plugin overrides font styling on all pages (not just pages where galleries or KORA objects sit). See the differences in "Explore" in the screenshot above. Initially I though it was bringing data from the twenty thirteen plugin, but it's overriding font there as well.

RE layout, see this page: http://vaarchaeology.matrix.msu.edu/index.php/rocketts/

There is a Leaflet map in the code that's getting either squished off screen or covered up entirely when the plugin is activated. It's also causing the word cloud image to resize and move around. 
![koraon](https://cloud.githubusercontent.com/assets/13810938/18091868/3c2cfd82-6e98-11e6-8edb-a3d69b52344a.JPG)

Here's what it looks like when KORA Connect is disabled.
![koraoff](https://cloud.githubusercontent.com/assets/13810938/18091966/88cb6228-6e98-11e6-9a59-84e44f08bd20.JPG)

**Comment by samcarne** [comment]
I see the issue here. When the plugin was built it was not kept in mind that the styles would be overriding the dashboard and also the theme (the theme was just brought to my attention).  I will be modifying the styles for the plugin so that those styles will not affect the theme.

**Comment by aejolene** [comment]
Fantastic! That will be a huge improvement for look and feel. Will this help the disappearing map/moving page element issue? My colleague had some success placing individual KORA objects into an HTML grid, but it was pretty clunky and I'd like to avoid that if possible so my pages remain responsive on different monitors.

**Comment by watrall** [comment]
Not sure how this will impact responsiveness.  At this stage, I just want to make sure that the regular, screen sized layout isn't broken

**Comment by watrall** [comment]
@aejolene - @samcarne has fixed the front-end layout issues and has tested fix on WP 2013, 2014, 2015 (and will do WP 2016 today).  In addition, she is working on some additional known front end layout issues.  We're going to push an updated version on Friday by close of business

**Comment by aejolene** [comment]
Great news; thanks to everyone!

**Comment by watrall** [comment]
@aejolene - we're updating your VA Archaeology install with the new plugin build in order to do some testing with your content (see if things are still broken in terms of layout).  You don't have to do anything.  FYI - this build breaks the full record/detail page...which we'll fix shortly

**Comment by aejolene** [comment]
Great. Thanks! I'm not working on the site today, so you all have free
reign.

**Comment by watrall** [comment]
@aejolene - Have a look at the rockets page.  Are you seeing any significant layout issues?

**Comment by aejolene** [comment]
The thumbnails are about 4x bigger than they were before, but the other elements displaying correctly. Thanks!

**Comment by aejolene** [comment]
I just tested individual objects within tables (both in a plain HTML table and using a layout plugin (Tailor). Both scaled the KORA thumbnails just perfectly. This is looking great! I'm also seeing that the font is consistent with the theme. Thanks to everyone!

**Comment by watrall** [comment]
@aejolene - we think that the latest version of the plugin deals with your layout issues (and a bunch of other things).  @seilagonzalez very kindly updated the version which is installed on your website...so you don't have to do anything. I'm closing this issue.  If anything crops up, open another issue

**Comment by aejolene** [comment]
Thank you @seilagonzalez and all! I've been working with layout over the past couple of days and everything is working wonderfully.
